### PR TITLE
Add watchify

### PR DESCRIPTION
**Pull request by samccone**
##### With watchify

screen shot 2015-07-01 at 3 27 50 pm

##### Without watchify

screen shot 2015-07-01 at 3 29 54 pm

#### perf measure patch

screen shot 2015-07-01 at 3 30 16 pm

----------------

would love to get some other people to post their findings

### CODE REVIEW

**Comment by samccone** [comment]
xref #11

**Comment by samccone** [comment]
@jenius let me know if there is anything else I can do here :clap:

**Comment by hhsnopek** [comment]
looks good to me :+1:

**Comment by samccone** [comment]
thx :heart:

**Comment by kylemac** [comment]
will get this on npm as soon as @jenius adds me as a contrib :person_frowning:

**Pull request merged**
