### PR TITLE
Add browserify injector

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
https://github.com/carrot/roots-browserify/issues/23 should satisfy this.

### CODE REVIEW

**Comment by jenius** [comment]
Lovely. Good work, thanks @SevereOverfl0w!

**Comment by jenius** [comment]
Two small comments before merge:

1. Could you squash be065e8 and 1ce2820 together?
2. Could you document this feature in the readme?

**Comment by SevereOverfl0w** [comment]
Is there any way for me to see what way I've reduced coverage? I have an idea, but I'd like to know specifically.

**Comment by kylemac** [comment]
@SevereOverfl0w one way is to run the coverage script locally, `npm run coverage` 

https://github.com/carrot/roots-browserify/blob/master/package.json#L51

**Comment by SevereOverfl0w** [comment]
Ah, didn't even think to look for that. Looks like the issue is that I
don't at any point test for unprefixed calls.. hmm... may have an idea for
that.

**Comment by SevereOverfl0w** [comment]
Okay, resolved. Thanks for that @kylemac.

**Pull request merged**
